site_name: 'ESIIL HYR-SENSE workshop'
site_description: 'Central resource for NASA-ESIIL HYR-SENSE workshop'
site_author: ESIIL and NASA staff
site_url: https://cu-esiil.github.io/HYR-SENSE

# Repository
repo_name: HYR-SENSE
repo_url: https://github.com/CU-ESIIL/HYR-SENSE
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2023 University of Colorado Boulder'

# Page tree
nav:
  - Home: index.md
  - Resources:
       - Code of Conduct: resources/code-of-conduct.md
       - Participant agreement: resources/participant_agreement.md
       - Cyverse basics: resources/cyverse_basics.md
       - Github basics: resources/github_basics.md
       - Cyverse hacks: resources/cyverse_hacks.md
       - Virtual Pre-event trainings: resources/hyr-sense_virtual_trainings.md

# Configuration
theme:
  highlightjs: true
  name: material
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'assets/esiil_content/ESIIL_logo.png'
  favicon: 'assets/esiil_content/favicon.ico'
  # setting features for the navigation tab
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - toc.follow
    - content.code.copy
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: white)"
      primary: 'white'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

# Options
extra:
  social:
    - icon: fontawesome/brands/github
     # link: https://github.com/cu-esiil/

extra_css:
  - stylesheets/extra.css

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
